# hash:sha256:a99e005c907b0d47f78691b997f9269e85ae2c03297ba83a1f227c1890b30ab5
FROM registry.acmecorp-edge.codeocean.com/codeocean/r-base:4.2.1-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /

ENV Tuatara=9
